version: "3.8"

services:
  gateway:
    build: .
    container_name: gateway-app
    ports:
      - "2399:2399"
    env_file:
      - .env
    environment:
      - DEV_ENV=development
    restart: unless-stopped
    networks:
      - dass_private

networks:
  dass_private:
    external: true